version: 1
author: Dizzy
language: Powershell
image: mcr.microsoft.com/powershell
code: /code
workdir: /code/%year%/%zeroday%
cmd: pwsh -command ./scenario.ps1
daypath: %year%/%zeroday%
inputfile: %year%/%zeroday%/input.txt
answerfile: %year%/%zeroday%/answer.txt
notty: true
